### PR TITLE
Build DEFAULT_RUNTIME_OPTIONS during instantiation 

### PR DESCRIPTION
**Pull request by nicerloop**
This is required to use cucumber-junit-platform-engine with SerenityReporter plugin

### CODE REVIEW

**Comment by wakaleo** [comment]
Hi, sorry, missed this PR - could you give me some context about what it does?

**Comment by nicerloop** [comment]
I try to use serenity with cucumber-junit-platform-engine. This applies equally to serenity-cucumber6, as the assumption that cucumber scenarios are launched from junit4 still holds and creates exactly the same problems.

I have published a reproduction example: https://github.com/nicerloop/serenity-cucumber-starter/tree/use-cucumber-junit-platform-engine

**Comment by wakaleo** [comment]
Could you raise the PR against the cucumber6 code base? This one is no longer maintained.

**Comment by nicerloop** [comment]
Done. https://github.com/serenity-bdd/serenity-cucumber6/pull/36

**Pull request closed without merging**
